// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC60vR9if21As67FtWnVKKZsWzsYi-0Jfg',
    appId: '1:350617376160:web:fe6ec3d136d0fd673280c5',
    messagingSenderId: '350617376160',
    projectId: 'superbai-app',
    authDomain: 'superbai-app.firebaseapp.com',
    storageBucket: 'superbai-app.firebasestorage.app',
    measurementId: 'G-E02LJ0ENDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPptgp2kV0MADJOVoYdAxpdQguFl-5euw',
    appId: '1:350617376160:android:191fc8748630f9f43280c5',
    messagingSenderId: '350617376160',
    projectId: 'superbai-app',
    storageBucket: 'superbai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClYQbAqcKoCVq-rwSDrbirCFUQA3ev85o',
    appId: '1:350617376160:ios:0ae51aa0d18431843280c5',
    messagingSenderId: '350617376160',
    projectId: 'superbai-app',
    storageBucket: 'superbai-app.firebasestorage.app',
    iosBundleId: 'com.example.superbai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClYQbAqcKoCVq-rwSDrbirCFUQA3ev85o',
    appId: '1:350617376160:ios:0ae51aa0d18431843280c5',
    messagingSenderId: '350617376160',
    projectId: 'superbai-app',
    storageBucket: 'superbai-app.firebasestorage.app',
    iosBundleId: 'com.example.superbai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC60vR9if21As67FtWnVKKZsWzsYi-0Jfg',
    appId: '1:350617376160:web:24ad72e07b6301bc3280c5',
    messagingSenderId: '350617376160',
    projectId: 'superbai-app',
    authDomain: 'superbai-app.firebaseapp.com',
    storageBucket: 'superbai-app.firebasestorage.app',
    measurementId: 'G-6YRG43ND3L',
  );
}
